# Generated by Django 2.1.3 on 2019-03-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190226_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='ロゴ'),
        ),
    ]
